#!/bin/bash
if [[ -d /home/user/restore ]]
then
	rm -r /home/user/restore
fi
mkdir /home/user/restore
backup_dirname=$(find /home/user -name Backup-* | sort | tail -n 1)
for file in $(ls $backup_dirname)
do
	if [[ -z $(echo $file | grep -E "*.[0-9]{4}-[0-0]{2}-[0-9]{2}") ]]
	then
		cp $backup_dirname/$file /home/user/restore/$file
	fi
done
